# Generated by Django 6.0 on 2025-12-04 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('texts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WritingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writing_type', models.CharField(max_length=100)),
                ('user_writing', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('word_count', models.IntegerField(default=0)),
                ('excerpt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='texts.textexcerpt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WritingStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('last_writing_date', models.DateField(blank=True, null=True)),
                ('total_sessions', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='writing_streak', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
