# Generated by Django 6.0 on 2025-12-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextExcerpt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('writing_type', models.CharField(max_length=100)),
                ('style', models.CharField(choices=[('descriptive', 'Descriptive'), ('narrative', 'Narrative'), ('dialogue', 'Dialogue'), ('poetic', 'Poetic'), ('expository', 'Expository')], max_length=50)),
                ('source_work', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['author', 'title'],
                'indexes': [models.Index(fields=['writing_type'], name='texts_texte_writing_ed7974_idx'), models.Index(fields=['style'], name='texts_texte_style_7cffc1_idx')],
            },
        ),
    ]
